development: &common
  adapter:        postgresql
  sequel_adapter: postgres
  encouding:      utf8
  reconnect:      false
  database:       tdd_sandwich_development
  pool:           5
  user:           your_user
  password:       your_password
  host:           localhost

test:
  <<: *common
  database:       c_bulz_test

production:
  <<: *common
  database:       c_bulz_production

# The next file will override this file
# <%= IO.read("config/database.local.yml") if File.exists?("config/database.local.yml") %>
